import os
import glob
import numpy as np
import cv2 as cv
import torch
from skimage import measure
from model import UNet

def load_patient_slices(patient_dir_path):
    slices = sorted(glob.glob(os.path.join(patient_dir_path, '*_*.tif')))
    images = [s for s in slices if "mask" not in s]

    volume_slices = []
    for i in images:
        img = cv.imread(i)
        img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
        img = img.astype(np.float32) / 255.0
        img = np.transpose(img, (2, 0, 1))
        volume_slices.append(img)

    return torch.tensor(np.array(volume_slices), dtype=torch.float32), images

def generate_3D_mesh(model_path, patient_dir_path, mesh_name="TumorMesh.obj"):
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Loading model
    model = UNet(in_channels=3, out_channels=1).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    tensor_slices, images = load_patient_slices(patient_dir_path)
    print(f"Loaded {len(tensor_slices)} slices from {patient_dir_path}\nHaving Shape: {tensor_slices.shape}")

    predicted_masks = []
    with torch.no_grad():
        # looping through all individual slices
        for i in range(tensor_slices.shape[0]):
            slice_tensor = tensor_slices[i].unsqueeze(0).to(device)
            prediction = model(slice_tensor)
            prediction = torch.sigmoid(prediction).squeeze().cpu().numpy()
            binary_mask = (prediction > 0.5).astype(np.uint8)
            # Appending the actual binary boundary grid
            predicted_masks.append(binary_mask)

    voxel_grid = np.stack(predicted_masks, axis=0)

    if voxel_grid.sum() == 0:
        print("[Warning] No tumor segments detected for this profile. Mesh file skipped.")
        return

    # Running marching cubes math
    vertices, faces, normals, values = measure.marching_cubes(voxel_grid, 0.5)

    # Exporting to standard .obj format
    with open(mesh_name, "w") as f:
        f.write("# Wavefront OBJ generated by MedTech Spatial AI\n")
        for v in vertices:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")
        for n in normals:
            f.write(f"vn {n[0]} {n[1]} {n[2]}\n")
        for face in faces:
            f.write(f"f {face[0]+1}//{face[0]+1} {face[1]+1}//{face[1]+1} {face[2]+1}//{face[2]+1}\n")

    print(f"[Success] 3D reconstruction complete for: {mesh_name}")

if __name__ == "__main__":
    patient_files = glob.glob(os.path.join(".", "lgg-mri-segmentation", "kaggle_3m", "*"))
    patient_files = [i for i in patient_files if "data_images" not in i and os.path.isdir(i)]
    if patient_files:
        test_patient = patient_files[0]
        generate_3D_mesh("best_unet_model.pth", test_patient, "TumorMesh.obj")
    else:
        print("No patient folders located.")
